#Global configuration
spring.application.name=safetynet

#Tomcat configuration
server.port=8080

#Log level configuration
logging.level.root=ERROR
logging.level.com.openclassroopms=INFO
logging.level.org.springframework.boot.web.ebedde.tomcat=INFO

com.openclassrooms.safetynet.apiUrl=http://localhost:9000
